nekidblog/nekidblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postsapp.urls')),
    path('', include('subscriptionsapp.urls')),
]

nekidblog/postsapp/urls.py
from django.urls import path
import postsapp.views as postsapp
from django.contrib.auth import urls


app_name = 'postsapp'


urlpatterns = [
    #path('', postsapp.login, name='login'),
    path('', postsapp.LoginView.as_view(), name="login"),
    path('add/', postsapp.CreatePost.as_view(), name='add_post'),
    #path('add/', postsapp.add_post, name='add_post'),
    path('blogs/', postsapp.BlogList.as_view(), name='all_blogs'),
    path('post/<pk>', postsapp.PostRead.as_view(), name='post_read'),
    path('lenta/', postsapp.lenta_news, name='lenta_news'),
    # path('add/', ordersapp.add_order, name='add_order'),
    # path('update/<pk>/', ordersapp.OrderUpdateView.as_view(), name='order_update'),
    # path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

nekidblog/subscriptionsapp/urls.py
from django.urls import path
import subscriptionsapp.views as subscriptionsapp



app_name = 'subscriptionsapp'


urlpatterns = [
    path('subscribe/<pk>/', subscriptionsapp.subscribe, name='subscribe'),
    path('unsubscribe/<pk>/', subscriptionsapp.unsubscribe, name='unsubscribe'),
    path('subscriptions/', subscriptionsapp.UserSubscriptionsList.as_view(), name='my_subscriptions'),
    # path('authors/', postsapp.AuthorList.as_view(), name='all_authors'),

]

nekidblog/subscriptionsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from postsapp.models import Blog


class Subscription(models.Model):
    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
    subscriber = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscription')
    source = models.ForeignKey(Blog, on_delete=models.CASCADE)
    is_active = models.BooleanField(verbose_name='активна', default=True)

# Create your models here.

nekidblog/subscriptionsapp/views.py
#from django.shortcuts import render
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, HttpResponse, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from .models import Subscription
from postsapp.models import Blog, Post


def subscribe(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    subscription = Subscription.objects.filter(subscriber=request.user, source=blog).first()
    if not subscription:
        subscription = Subscription(subscriber=request.user, source=blog)
    elif subscription.is_active == False:
        subscription.is_active = True
    else:
        print('Вы уже подписаны')
    subscription.save()
    return HttpResponseRedirect(reverse('subscriptionsapp:my_subscriptions'))


def unsubscribe(request, pk):
    subscription = Subscription.objects.filter(pk=pk).first()
    subscription.is_active = False
    subscription.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class UserSubscriptionsList(ListView):
    template_name = "subscriptionsapp/subscriptions.html"
    model = Subscription

    def get_queryset(self):
        return Subscription.objects.filter(subscriber=self.request.user, is_active=True).select_related()


# Create your views here.

nekidblog/subscriptionsapp/templates/subscriptionsapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
{#        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">#}
{#        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">#}
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">

            {% block content %}

            {% endblock %}
        </div>
</body>
</html>

nekidblog/subscriptionsapp/templates/subscriptionsapp/subscriptions.html
{% extends 'subscriptionsapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h4>Ваши подписки {{ user }}</h4>
        <br>
        {% include 'postsapp/menu.html' %}
        {% include 'subscriptionsapp/subscriptions_table_part.html' %}

    </div>
    <br />
    <div>
        <a href="{% url 'postsapp:add_post' %}"
           class="btn btn-success">
            Назад в блог
        </a>
    </div>
    <br />
    <footer>
        <div class="container">
            <div class="row">
                <p class="copyright text-muted">Copyright &copy; NekidaemRu</p>
            </div>
        </div>
    </footer>

{% endblock %}

nekidblog/subscriptionsapp/templates/subscriptionsapp/subscriptions_table_part.html
{% load static %}

<table class="table" id="author-table">
    <tr>
        <th>
            <h4>Автор Блога:</h4>
        </th>

        <th>
            <h4>Тематика Блога:</h4>
        </th>


    </tr>
    {% for subscr in object_list %}
    <tr>
        <td>
            {{subscr.source.author.username}}
        </td>

        <td>
            {{subscr.source.blog_theme}}
        </td>
        <td>

            <a href="{% url 'subscriptionsapp:unsubscribe' subscr.pk %}">
                 Отписаться
            </a>
        </td>

    </tr>
    {% endfor %}
</table>