nekidblog/nekidblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postsapp.urls')),
    path('', include('subscriptionsapp.urls')),
]

nekidblog/postsapp/urls.py
from django.urls import path
import postsapp.views as postsapp
from django.contrib.auth import urls


app_name = 'postsapp'


urlpatterns = [
    #path('', postsapp.login, name='login'),
    path('', postsapp.LoginView.as_view(), name="login"),
    path('add/', postsapp.CreatePost.as_view(), name='add_post'),
    #path('add/', postsapp.add_post, name='add_post'),
    path('blogs/', postsapp.BlogList.as_view(), name='all_blogs'),
    path('post/<pk>', postsapp.PostRead.as_view(), name='post_read'),
    path('lenta/', postsapp.lenta_news, name='lenta_news'),
    # path('add/', ordersapp.add_order, name='add_order'),
    # path('update/<pk>/', ordersapp.OrderUpdateView.as_view(), name='order_update'),
    # path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

nekidblog/subscriptionsapp/urls.py
from django.urls import path
import subscriptionsapp.views as subscriptionsapp



app_name = 'subscriptionsapp'


urlpatterns = [
    path('subscribe/<pk>/', subscriptionsapp.subscribe, name='subscribe'),
    path('unsubscribe/<pk>/', subscriptionsapp.unsubscribe, name='unsubscribe'),
    path('subscriptions/', subscriptionsapp.UserSubscriptionsList.as_view(), name='my_subscriptions'),
    # path('authors/', postsapp.AuthorList.as_view(), name='all_authors'),

]

nekidblog/postsapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_theme = models.CharField(verbose_name='тема блога', max_length=50)


class Post(models.Model):
    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    post_title = models.CharField(verbose_name='заголовок поста', max_length=50)
    post_body = models.TextField(verbose_name='текст поста', blank=True)
    date_created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
# Create your models here.

nekidblog/postsapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from postsapp.models import Post
from django.contrib.auth.models import User as BlogAuthor


class BlogAuthorLoginForm(AuthenticationForm):

    class Meta:
        model = BlogAuthor
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(BlogAuthorLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class PostForm(forms.ModelForm):
   class Meta:
       model = Post
       exclude = ('blog', 'date_created', )
       #exclude = ('date_created', )

   def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       for field_name, field in self.fields.items():
           field.widget.attrs['class'] = 'form-control'

nekidblog/postsapp/views.py
from django.shortcuts import render, reverse
from django.contrib import auth
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic import ListView, CreateView
from postsapp.forms import BlogAuthorLoginForm, PostForm
from .models import Blog, Post
from subscriptionsapp.models import Subscription
from .utils import send_newpost_mail


# def login(request):
#     title = 'вход'
#
#     login_form = BlogAuthorLoginForm(data=request.POST)
#     if request.method == 'POST' and login_form.is_valid():
#         username = request.POST['username']
#         password = request.POST['password']
#         user = auth.authenticate(username=username, password=password)
#         if user:
#             auth.login(request, user)
#             form = PostForm()
#             context = {'post_form': form}
#             return render(request, 'postsapp/index.html', context)
#     context = {'title': title, 'login_form': login_form}
#     return render(request, 'postsapp/login.html', context)

class LoginView(TemplateView):
    template_name = "postsapp/login.html"

    def dispatch(self, request, *args, **kwargs):
        context = {}
        title = 'вход'
        login_form = BlogAuthorLoginForm(data=request.POST)
        if request.method == 'POST'and login_form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(request, username=username, password=password)
            if user:
                auth.login(request, user)
                form = PostForm()
                context['post_form'] = form
                return render(request, 'postsapp/index.html', context)
        context['title'] = title
        context['login_form'] = login_form
        return render(request, self.template_name, context)


# def add_post(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             blog = Blog.objects.filter(author=request.user).first()
#             form.instance.blog = blog
#             form.save()
#             subscribers = Subscription.objects.filter(source=blog, is_active=True).select_related()
#             addressee_list = []
#             for subscriber in subscribers:
#                 addressee = subscriber.subscriber
#                 addressee_list.append(addressee.email)
#             sender = request.user
#             post = Post.objects.filter(blog=blog).last()
#             pk = post.pk
#             send_newpost_mail(sender, addressee_list, pk)
#             form = PostForm()
#     else:
#         form = PostForm()
#     context = {'post_form': form}
#     return render(request, 'postsapp/index.html', context)


class CreatePost(CreateView):
    model = Post
    fields = ('post_title', 'post_body')
    template_name = 'postsapp/index.html'

    def get_success_url(self):
        return reverse('postsapp:add_post')

    def get_context_data(self, **kwargs):
        context = super(CreatePost, self).get_context_data(**kwargs)
        form = PostForm()
        context['post_form'] = form
        return context

    def form_valid(self, form):
        blog = Blog.objects.filter(author=self.request.user).first()
        form.instance.blog = blog
        super().form_valid(form)
        subscribers = Subscription.objects.filter(source=blog, is_active=True).select_related()
        addressee_list = []
        for subscriber in subscribers:
            addressee = subscriber.subscriber
            addressee_list.append(addressee.email)
        sender = self.request.user
        post = Post.objects.filter(blog=blog).last()
        pk = post.pk
        send_newpost_mail(sender, addressee_list, pk)
        return super().form_valid(form)


class BlogList(ListView):
    template_name = "postsapp/blogs.html"
    model = Blog

    def get_queryset(self):
        return Blog.objects.all().select_related()


def lenta_news(request):
    lenta_news = {}
    subscriptions = Subscription.objects.filter(subscriber=request.user, is_active=True)
    for item in subscriptions:
        lenta = Post.objects.filter(blog=item.source)
        lenta = sorted(lenta, key=lambda x: x.date_created, reverse=True)
        lenta_news[item.source] = lenta
    context = {
        'lenta': lenta_news
        }
    return render(request, 'postsapp/lenta_news.html', context)


class PostRead(DetailView):
   model = Post

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['title'] = 'пост/просмотр'
       return context

nekidblog/postsapp/templates/postsapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{#        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">#}
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">

            {% block content %}

            {% endblock %}
        </div>
</body>
</html>

nekidblog/postsapp/templates/postsapp/blogs.html
{% extends 'postsapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        {% include 'postsapp/menu.html' %}
        {% include 'postsapp/blogs_table_part.html' %}

    </div>
    <br />
    <br />
    <footer>
        <div class="container">
            <div class="row">
                <p class="copyright text-muted">Copyright &copy; NekidaemRu</p>
            </div>
        </div>
    </footer>
    <br>
    <div>
        <a href="{% url 'postsapp:add_post' %}"
           class="btn btn-success">
            Назад в блог
        </a>
    </div>

{% endblock %}

nekidblog/postsapp/templates/postsapp/blogs_table_part.html
{% load static %}

<table class="table" id="author-table">
    <tr>
        <th>
            <h4>Автор Блога:</h4>
        </th>

        <th>
            <h4>Тематика Блога:</h4>
        </th>


    </tr>
    {% for blog in object_list %}
    <tr>
        <td>
            {{blog.author.username}}
        </td>

        <td>
            {{blog.blog_theme}}
        </td>

        <td>
            <a href="{% url 'subscriptionsapp:subscribe' blog.pk %}">
                Подписаться
            </a>

        </td>
    </tr>
    {% endfor %}
</table>

nekidblog/postsapp/templates/postsapp/index.html
{% extends 'postsapp/base.html' %}
{% load static %}

{% block content %}

    <h4>Добро пожаловать {{ user }}</h4>
        <br>

    {% include 'postsapp/menu.html' %}

    <br>
    <form class="form-horizontal" method="post" action="{% url 'postsapp:add_post' %}">
        {% csrf_token %}
        {{ post_form.as_p }}
{#        {{ form.as_p }}#}
        <br>
{#        <input type="submit" value="Save" />#}
        <button type="button" class="btn btn-default">Отмена</button>
        <button type="submit" class="btn btn-primary">Опубликовать</button>
    </form>

{% endblock %}

nekidblog/postsapp/templates/postsapp/lenta_news.html
{% extends 'postsapp/base.html' %}
{% load static %}

{% block content %}
    {% include 'postsapp/menu.html' %}
    {% for blog, posts in lenta.items %}
        <div>
            <h4>{{blog.author}}  <span style="font-style: italic">{{blog.blog_theme}}</span></h4>

            {% for post in posts %}
                <h5>{{post.post_title}}  <span style="color: blue; font-style: italic; font-size: 14px">{{post.date_created}}</span></h5>
                <p>
                    {{post.post_body}}
                </p>
            {% endfor %}
        </div>
        <br>
    {% endfor %}
    <br>
    <div>
        <a href="{% url 'postsapp:add_post' %}"
           class="btn btn-success">
            Назад в блог
        </a>
    </div>
    <br />
    <footer>
        <div class="container">
            <div class="row">
                <p class="copyright text-muted">Copyright &copy; NekidaemRu</p>
            </div>
        </div>
    </footer>
{% endblock %}

nekidblog/postsapp/templates/postsapp/login.html
{% extends 'postsapp/base.html' %}
{% load static %}

{% block content %}
    <h1>Вход в блог</h1>
    {% if error %}
        <div style="color:red;">{{ error }}</div>
    {% endif %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

{% endblock %}


{#{% block content %}#}
{#    <h1>Вход на сайт</h1>#}
{#    {% if error %}#}
{#        <div style="color:red;">{{ error }}</div>#}
{#    {% endif %}#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        <input type="text" name="username" placeholder="Логин">#}
{#        <input type="password" name="password" placeholder="Пароль">#}
{#        <input type="submit" value="Войти">#}
{#    </form>#}
{##}
{#{% endblock %}#}

nekidblog/postsapp/templates/postsapp/menu.html
{% load static %}

<ul>
        <li>
            <a href="{% url 'postsapp:all_blogs' %}">
                Все блоги
            </a>
        </li>

        <li>
            <a href="{% url 'subscriptionsapp:my_subscriptions' %}">
                Мои подписки
            </a>
        </li>

        <li>
            <a href="{% url 'postsapp:lenta_news' %}">
                Лента новостей
            </a>
        </li>
    </ul>

nekidblog/postsapp/templates/postsapp/post_detail.html
{% extends 'postsapp/base.html' %}
{% load static %}

{% block content %}
        <div>
            <h5>{{object.post_title}}  <span style="color: blue; font-style: italic; font-size: 14px">{{object.date_created}}</span></h5>
            <p>
                {{object.post_body}}
            </p>
        </div>
        <br>

{% endblock %}